import GoogleAnalytics from '@/components/ga4/GoogleAnalytics';
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import AuthContext from '../components/providers/AuthContext'

const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID;

const inter = Inter({subsets: ['latin']})


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <GoogleAnalytics GA_MEASUREMENT_ID={GA_MEASUREMENT_ID}/>
        <body className={inter.className}>
        <AuthContext>{children}</AuthContext>
        </body>
        </html>
    )
}
