import GoogleAnalytics from "@/components/ga4/GoogleAnalytics";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SocketProvider } from "@/components/context/socket";
import styles from "./layout.module.css";

const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mingle",
  description: "Generated by mingle",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/white_logo.svg" sizes="any" />
      <SocketProvider>
        <GoogleAnalytics GA_MEASUREMENT_ID={GA_MEASUREMENT_ID} />
        <body className={inter.className}>
          <div id={styles.container}>{children}</div>
        </body>
      </SocketProvider>
    </html>
  );
}
